### ISSUE TITLE
Update Copr Repo

### ISSUE THREAD

**Issue by ghost** [tpokorra/lbs-nextcloud#4]
Hello,

Thank you for the https://copr.fedorainfracloud.org/coprs/tpokorra/nextcloud/ REPO. Can you please update it to 2.3.1?
Thank you in advance.

pic

**Comment by tpokorra** [comment]
I am not maintaining the repo https://copr.fedorainfracloud.org/coprs/tpokorra/nextcloud/ anymore, because the package is now part of Fedora and Epel7: https://apps.fedoraproject.org/packages/nextcloud-client

Please test nextcloud-client 2.3 from the testing repo of Fedora, or if you are on CentOS, the testing repo of Epel.
